export enum ErrorCode {
    // ===== Users =====
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    EMAIL_ALREADY_USED = 'EMAIL_ALREADY_USED',
    PHONE_ALREADY_USED = 'PHONE_ALREADY_USED',
    CANNOT_DELETE_YOURSELF = 'CANNOT_DELETE_YOURSELF',

    // ===== Auth =====
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
    ACCOUNT_DISABLED = 'ACCOUNT_DISABLED',

    // ===== Tontines =====
    TONTINE_NOT_FOUND = 'TONTINE_NOT_FOUND',
    INVALID_MEMBER_COUNT = 'INVALID_MEMBER_COUNT',
    TONTINE_CANNOT_BE_UPDATED = 'TONTINE_CANNOT_BE_UPDATED',
    TONTINE_STATUS_INVALID = 'TONTINE_STATUS_INVALID',

    // ===== Memberships =====
    MEMBERSHIP_NOT_FOUND = 'MEMBERSHIP_NOT_FOUND',
    MEMBERSHIP_ALREADY_EXISTS = 'MEMBERSHIP_ALREADY_EXISTS',
    MEMBERSHIP_LIMIT_REACHED = 'MEMBERSHIP_LIMIT_REACHED',
    INVALID_MEMBERSHIP_STATUS = 'INVALID_MEMBERSHIP_STATUS',

    // ===== Contributions =====
    CONTRIBUTION_NOT_FOUND = 'CONTRIBUTION_NOT_FOUND',

    // ===== Cycles =====
    CONTRIBUTION_CYCLE_NOT_FOUND = 'CONTRIBUTION_CYCLE_NOT_FOUND',

    // ===== Generic =====
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    DATABASE_ERROR = 'DATABASE_ERROR',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}